### ISSUE TITLE
Auto Update Box Collider of LG_Ladder depend on Thickness and Width value

### ISSUE THREAD

**Issue by Flowaria** [GTFO-Modding/GTETO#18]
Yes

**Comment by Panthr75** [comment]
Thickness and width are fixed aren't they?

**Comment by Flowaria** [comment]
Seems they are customizable and it resolved by LevelBuilder automatically probably for customizing interaction size depends on layouts

**Comment by Panthr75** [comment]
Can you send some code snippets? I want an idea of what I need to do
